### ISSUE TITLE
Compilation failure with "org.twak.utils.geom.ObjDump"

### ISSUE THREAD

**Issue by vivzqs** [twak/chordatlas#19]
org/twak/tweed/gen/MeshCanvasGen.java:[203,21]

FLIP_Y_UV_ON_WRITE not found

**Comment by twak** [comment]
Thanks for the report, this was a new flag that I forgot to commit to ObjDump in JUtils. 

This commit should fix it
https://github.com/twak/jutils/commit/67ae6c4dbcfeff0d80fa6760f3c5d4d128adf8b9
