### ISSUE TITLE
integrated obj model export

### ISSUE THREAD

**Issue by Wii92** [twak/chordatlas#23]
Thanks for providing this awesome tool!

Is there any way to export the integrated minimesh models?

**Comment by twak** [comment]
hey,

You can get similar meshes using systems such as this: https://github.com/retroplasma/earth-reverse-engineering

Chordatlas has an option to export to OBJ. If you show the minimesh, it might export it?

**Comment by Wii92** [comment]
I tried it, but an empty obj model is exported. 

Maybe the earth-reverse-engineering is  alternative choice

**Comment by twak** [comment]
Ah yeah, your probably need to have to do some coding: MiniGen would have to implement IDumpObjs, then copy the implementation from JmeGen:
```
	@Override
	public void dumpObj( ObjDump dump ) {
		Jme3z.dump(dump, gNode, 0);
	}
```
