### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by davethejoy** [twak/chordatlas#28]
I am building a new jar file using Gurobi 9.0.2 under docker, and I am getting the following error

Steps to reproduce the behaviour:
1) update Docker file to use Gurobi to 9.0.2
2) update chordatlas.iml to use Gurobi 9.0.2
3) update pom.xml to use Gurobi 9.0.2
4) perform docker build

I am Running Docker under Macosx Catalina
Here is the error
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:39 min
[INFO] Finished at: 2020-07-06T15:19:54+00:00
[INFO] Final Memory: 15M/129M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chordatlas: Could not resolve dependencies for project org.twak.chordatlas:chordatlas:jar:0.0.1: Failed to collect dependencies at org.geotools:gt-xml:jar:19.1: Failed to read artifact descriptor for org.geotools:gt-xml:jar:19.1: Could not transfer artifact org.geotools:gt-xml:pom:19.1 from/to jcenter (http://jcenter.bintray.com): Access denied to: http://jcenter.bintray.com/org/geotools/gt-xml/19.1/gt-xml-19.1.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command '/bin/sh -c mvn install' returned a non-zero code: 1
```
It appears like Jcenter expects HTTPS instead
whenever I tried to open the URL as HTTPS, I get the following POST
https://jcenter.bintray.com/org/geotools/gt-xml/19.1/gt-xml-19.1.pom
```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
```

am I missing something?

**Comment by twak** [comment]
Thanks for the report. It seems to have moved to 

https://repo.osgeo.org/repository/Geoserver-releases/org/geotools/gt-xml/19.1/gt-xml-19.1.pom

I guess this isn't related to Docker or Gurobi 9? Just that the maven ecosystem is crumbling? :(

Could you do a pull request for Gurobi 9? There's another user trying to get it working.

Things are looking busy here, I'll try to put a patch together look later in the week.

**Comment by davethejoy** [comment]
My collegue, Rose, shared a new POM file that fixed the problem. we can close this issue.

**Comment by twak** [comment]
I'd love to discuss what you and rooose want to use this for. Drop me an [email](https://vcg.leeds.ac.uk/profiles/twak/)?

**Comment by davethejoy** [comment]
Sure!
Please can you add "davethejoy" to I can upload my pull request? will contact you offline.

**Comment by davethejoy** [comment]
Email sent...
