### ISSUE TITLE
some questions of running with my own dataset

### ISSUE THREAD

**Issue by wyh9729** [twak/chordatlas#30]
Hello, I have two questions to ask. The first one is that I want to test with my own dataset, but I don't know how to get the minimesh in the sample dataset, because I use aerial data for large-scale reconstruction and get mesh of multiple buildings. How to deal with the overall mesh to obtain minimesh?

Second, how does the imported footprint correspond to its mesh? 

I am very interested in your work and have read your project code for many days. However, I am a beginner. I would appreciate it if you could explain your code organization structure for me!

Looking forward to your reply, thank you!

**Comment by twak** [comment]
Sorry, it's unlikely I can explain a 50kloc line of code project in a comment. When I'm in this situation I often find my self searching the codebase for the text from a button, then using my IDE's search functions to find out what it does.

Did you see the following wiki pages?
https://github.com/twak/chordatlas/wiki/interface-instructions-and-pipeline-videos
https://github.com/twak/chordatlas/wiki/datasets

in particular I've just linked [this video](https://www.youtube.com/watch?v=OP8PbY9XtFU) showing the alignment process.

**Comment by wyh9729** [comment]
Thank you very much for your reply. I may have to trouble you. How can I get the minimesh in your dataset from a large-scale mesh?

**Comment by twak** [comment]
apologies, I've just updated the above video link: https://www.youtube.com/watch?v=OP8PbY9XtFU

I think clicking the "+" button, then "+ mesh (minimesh)" will import an obj as a minimesh.

**Comment by wyh9729** [comment]
ok，thank you very much. I'll have a try~

**Comment by twak** [comment]
can we close this?
