### ISSUE TITLE
problems about the gis data

### ISSUE THREAD

**Issue by wyh9729** [twak/chordatlas#32]
Hello, I use the OSM data downloaded from OpenStreetMap and convert it into GML data with QGIS. However, when importing Chordatlas, the proportion of footprints has changed. I don't know why. 
As a result, I couldn't align mesh and footprint because of the wrong scale.
It is normal to preview footprint in QGIS in picture 1.
![QQ截图20201225143004](https://user-images.githubusercontent.com/44289618/103123030-b4bd4c00-46bd-11eb-9db2-27a2a0a78a4c.png)
and the result after importing into the chordatlas is as the second picture。
![QQ截图20201225143326](https://user-images.githubusercontent.com/44289618/103123126-2bf2e000-46be-11eb-876e-b580931f9432.png)

**Comment by twak** [comment]
Hey,

This is related to the coordinate system used for the data. Chordatlas interprets it as having each axis perpendicular with the same scale, which is usually a bad assumption.

I suggest using QGIS to transform your footprints into a suitable local CRS - you can find a suitable one using sites such as: https://epsg.io/

**Comment by wyh9729** [comment]
So you mean that choratlas uses the same coordinate system. As I saw in the dataset“regent_osm”, it is the "EPSG: 27700" coordinate system. I just need to convert the "EPSG: 4326" in my dataset to "EPSG: 27700"
![image](https://user-images.githubusercontent.com/44289618/103251275-2560b300-49b3-11eb-8e12-dbf76949e1c2.png)

**Comment by wyh9729** [comment]
Ah, I have solved this problem. Thank you. My data is in WSG 84 coordinate system, but it needs to be converted into Mercator coordinate system when inputting choraltas system. Thank you for your help
