### ISSUE TITLE
after importing tweedstreets, tools failed to load

### ISSUE THREAD

**Issue by wyh9729** [twak/chordatlas#33]
hello, following your tips, I add tweedstreets project to Debug Configurtions -> ClassPath, but Tools failed to load.
if I set the classpath to the chordatlas ,the tools come back. ps: I run the project following your guide seriously, I have already set the resources both in chordatlas and tweedstreet as resource in the project structure. I donnot know how to fix it , please help me . your sincerely.

![image](https://user-images.githubusercontent.com/44289618/111306482-33a99b80-8693-11eb-8ac6-c9607570b4b1.png)

**Comment by twak** [comment]
thanks for this. Which instructions are you following?

(I won't be able to fix anything for a few weeks at this point).

**Comment by wyh9729** [comment]
![image](https://user-images.githubusercontent.com/44289618/111461037-ad0ac200-8757-11eb-8928-ae18f9dcb71b.png)
just the instructions in this page, I've finished the steps  in both "terminal"part and "intellij"part in this picture, I've also watch the video named“ setting up the build in intellij” and follow it carefully，I'm sure my configuration is consistent with what you mentioned，I know the problem only based on my description ，Maybe it's hard to solve，But I'm still dying to get it right.
I have some suggestions. I would appreciate it if you could provide a more complete and specific guide document about the building and environment configuration of this code，I think the previous description is a bit brief，For example, how to run segnet-facade in the chordatlas，I am greatful for your help.
yours sincerely

**Comment by twak** [comment]
Setting the "Use classpath of module" in the "Run/Debug Configurations" of IntelliJ to "tweedstreets" seems to work here. Can you detail the command line statements which cause this problem?

![image](https://user-images.githubusercontent.com/127402/111770728-b05e9480-88a2-11eb-96c6-2533286e3830.png)

I'm sorry, but this isn't commercial software. I can't/won't provide industry level support.

**Comment by twak** [comment]
marking resolved....?
