### ISSUE TITLE
Utils folder

### ISSUE THREAD

**Issue by abhishek31704** [twak/chordatlas#34]
Hello, 

The following import files are not available in repository. 

import org.twak.utils.BitTwiddle;
import org.twak.utils.Mathz;
import org.twak.utils.collections.CountThings;
import org.twak.utils.geom.ObjDump;

import com.thoughtworks.xstream.XStream;

and ObjDump is not used.

**Comment by twak** [comment]
yes, you are correct - these files are the in the dependencies.
