### ISSUE TITLE
Own Data Information

### ISSUE THREAD

**Issue by abhishek31704** [twak/chordatlas#35]
Hi, 

I am trying to generate my own data and as input I need panorama and minimesh. I can get the building footprint using QGIS and for panorama images I used Pano Fetch google chrome plugin( The Pano Scrapper Plugin is said to be not working in the link given) 

1. How can I generate the mesh? Whether QGIS is used for this or the following link can be used?
   (https://github.com/tordanik/OSM2World/) 
2. I have Panorama Images using Pano Fetch.  How to generate Panos/todo.list which contain the panorama ID? 
3. In the readTrace file, 

what the following file/folder path should contain:
/home/twak/dump/blah
/home/twak/Desktop/frames.xml
/home/twak/Desktop/minimesh/ 

?

**Comment by twak** [comment]
The mesh pipeline is quite involved to get working.

1/ I would suggest using a tool such as [this](https://github.com/retroplasma/earth-reverse-engineering) and then manually [aligning](https://www.youtube.com/watch?v=OP8PbY9XtFU) the mesh.

2/ I do not not know anything about pano-fetch, so can't help. You can check out the example datasets for the expected data-format of the todo file. The panorama filenames encode the location and rotation of the panoramas.

3/ `ReadTrace` is very rough code (working on GL calls from chrome) - I haven't used it for a while, and if you cannot understand the code, I suspect it would be difficult to use. I suggest using the above (much more refined) tool to create meshes today.
