### ISSUE TITLE
street information

### ISSUE THREAD

**Issue by buaadps** [twak/chordatlas#36]
hello，Thanks for your great work！
Apart from the paper itself, are you able to tell me about how were the roads in the rendering images generated?
Manually generated or fully automated？Looking forward to your reply.

**Comment by twak** [comment]
Hey! Which render are you discussing?

**Comment by buaadps** [comment]
![image](https://user-images.githubusercontent.com/28102532/145926664-3e0ab6d3-7670-49b3-9241-17503f3a17d8.png)
just like this

**Comment by twak** [comment]
Ah, I see the one! - the streets were made with CityEngine and the "complete streets" rules you can download from the Esri website. I think I had to edit the rules to create the big red buses.

There is a free trial of CityEngine available in most countries https://www.esriuk.com/en-gb/arcgis/products/arcgis-cityengine/trial

**Comment by buaadps** [comment]
Thank you very much for your patient answer！！
