### ISSUE TITLE
Is bigsur necessary to use bikegan? Can bikegan handle noisy mesh directly?

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [twak/chordatlas#38]
For example, I only want to generate texture for mesh, do I have to go through bigsur first, or is there an easy way for me to directly use frankengan to generate texture for the building, thanks!

**Comment by twak** [comment]
Hey kuaiqushangzixiba,

To create a single texture from the frankengan chain you can run a single bikegan network on a texture map generated for the mesh you should be able to get the results with [test.py](https://github.com/twak/bikegan/blob/master/test.py).

However, to recreate all of the frankengan chain (high resolution, separate window and door networks etc...) you would need to use chordatlas.

**Comment by kuaiqushangzixiba** [comment]
What are the inputs to test.py? I notice this sentence, --dataroot', required=False, help='path to images (should have subfolders trainA, trainB, valA, valB, etc)', I don't know java, So is there any way I can make sense of frankengan's input.... Thank you very much

**Comment by twak** [comment]
frankengan's inputs are a mesh. I'm not sure what that has to do with test.py?

**Comment by kuaiqushangzixiba** [comment]
![image](https://github.com/twak/chordatlas/assets/42159103/48f7bb89-bf34-4ee2-9fd6-f69face66739)
![image](https://github.com/twak/chordatlas/assets/42159103/b5f34cfb-242f-4a0d-a6d6-e1bab219bfed)
When I run test it appears as follows. How do I set the parameters

**Comment by twak** [comment]
I'm sorry, I haven't run this code for a long time and don't have any notes. Perhaps the author will know more? `test.py` is from [BicycleGAN](https://github.com/junyanz/BicycleGAN)
